### ISSUE TITLE
Auto update error

### ISSUE THREAD

**Issue by bigfacewo** [myoung34/docker-github-actions-runner#91]
```
Configuring

--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication


√ Connected to GitHub

# Runner Registration



A runner exists with the same name
√ Successfully replaced the runner
√ Runner connection is good

# Runner settings


√ Settings Saved.

.path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/actions-runner
Starting Runner listener with startup type: service
Started listener process
Started running service

√ Connected to GitHub

2021-03-11 03:03:53Z: Listening for Jobs
Runner update in progress, do not shutdown runner.
Downloading 2.277.1 runner
Waiting for current job finish running.
Generate and execute update script.
Runner will exit shortly for update, should back online within 10 seconds.
renamed '/actions-runner/_diag/SelfUpdate-20210311-030517.log' -> '/actions-runner/_diag/SelfUpdate-20210311-030517.log.failed'
Runner listener exited with error code 3
Runner listener exit because of updating, re-launch runner in 5 seconds.
Starting Runner listener with startup type: service
Started listener process
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn /actions-runner/bin/Runner.Listener ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /actions-runner/bin/Runner.Listener',
  path: '/actions-runner/bin/Runner.Listener',
  spawnargs: [ 'run', '--startuptype', 'service' ]
}

```
What's the problem?

**Comment by myoung34** [comment]
> Runner listener exit because of updating, re-launch runner in 5 seconds.

Its updating to 2.277.1  and bouncing. Choose latest or a different image

**Comment by bigfacewo** [comment]
The problem is that I use other mirror sources, which are not up-to-date.
